language: java

services:
  - docker

# skip install step
install: true

cache:
  directories:
  - $HOME/.m2

stages:
  - test
  - test-oc-and-k8s
  - test-restarts
  - deploy

jobs:
  include:
    - stage: test
      name: "Maven & cont. image build"
      language: java
      script: make build-travis test

    - stage: Kubernetes and Openshift tests
      name: "[oc • CMs] Full specs"
      env: BIN=oc VERSION=v3.9.0 CRD=0
      script: &oc-script-defaults
        - make build-travis
        - ./.travis/.travis.prepare.openshift.sh
        - ./.travis/.travis.test-oc-and-k8s.sh

    - stage:
      name: "Full specs [oc • CRs]"
      env: BIN=oc VERSION=v3.9.0 CRD=1
      script: *oc-script-defaults

    #- stage:
    #  env: BIN=oc VERSION=v3.10.0 CRD=0
    #  script: *oc-script-defaults

    - stage:
      name: "Full specs [K8s • CMs]"
      env: BIN=kubectl VERSION=v1.9.0 CRD=0 MINIKUBE_VERSION=v0.25.2
      script: &kc-script-defaults
        - make build-travis
        - ./.travis/.travis.prepare.minikube.sh
        - ./.travis/.travis.test-oc-and-k8s.sh

    - stage:
      name: "Full specs [K8s • CRs]"
      env: BIN=kubectl VERSION=v1.9.0 CRD=1 MINIKUBE_VERSION=v0.25.2
      script: *kc-script-defaults

    - stage:
      name: "Random restarts [oc • CMs]"
      env: BIN=oc VERSION=v3.9.0 CRD=0
      script:
        - make build-travis
        - ./.travis/.travis.prepare.openshift.sh
        - ./.travis/.travis.test-restarts.sh

    - stage:
      name: "Random restarts [K8s • CRs]"
      env: BIN=kubectl VERSION=v1.9.0 CRD=1 MINIKUBE_VERSION=v0.25.2
      script:
        - make build-travis
        - ./.travis/.travis.prepare.minikube.sh
        - ./.travis/.travis.test-restarts.sh

    - stage:
      name: "Cross namespaces (WATCHED_NAMESPACES=*) [oc • CMs]"
      env: BIN=oc VERSION=v3.9.0 CRD=0
      script: &cross-ns-defaults
      - make build-travis
      - ./.travis/.travis.prepare.openshift.sh
      - ./.travis/.travis.test-cross-ns.sh

    - stage:
      name: "Cross namespaces (WATCHED_NAMESPACES=*) [oc • CRs]"
      env: BIN=oc VERSION=v3.9.0 CRD=1
      script: *cross-ns-defaults

    - stage: deploy
      name: "Push container images"
      script:
        # release x.y.z or x.y.z-centos if there is a release
        # or release the latest image if building the master branch
        - ./.travis/.travis.release.images.sh
        # release maven artifacts
        - 'if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]] ; then make build-travis && ./mvnw -s ./.travis/settings.xml clean deploy; fi'
