version: v0.1.5-v1alpha1
operator:
  image:
    repository: quay.io/radanalyticsio/spark-operator
    tag: latest-released
    pullPolicy: IfNotPresent
  env:
    crd: false
    colors: true
    namespace: ""
  resources:
    limits:
      memory: 512Mi
      cpu: 500m
