apiVersion: radanalytics.io/v1
kind: SparkCluster
metadata:
  name: my-spark-cluster
spec:
  worker:
    instances: "2"
  master:
    instances: "1"
  customImage: radanalyticsio/openshift-spark:2.2-latest
