apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-cluster-with-data
  labels:
    radanalytics.io/kind: SparkCluster
data:
  config: |-
    worker:
      instances: "1"
    downloadData:
    - url: https://data.cityofnewyork.us/api/views/kku6-nxdu/rows.csv
      to: /tmp/
    - url: https://data.lacity.org/api/views/nxs9-385f/rows.csv
      to: /tmp/LA.csv
