---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-crd-operator
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: spark-operator-edit-resources
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
subjects:
- kind: ServiceAccount
  name: spark-crd-operator
  namespace: openshift-operators
