kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: sparkclusters.radanalytics.io
spec:
  group: radanalytics.io
  names:
    kind: SparkCluster
    listKind: SparkClusterList
    plural: SparkClusters
    singular: SparkCluster
  scope: Namespaced
  version: v1
